---
buoys:
  - 41002 # US-SE
  - 41004 # US-SE
  - 41008 # US-SE
  - 41009 # US-SE / east of Cocoa Beach
  - 41013 # US-SE
  - 41047 # US-SE
  - 42002 # West Gulf - 200 m east of Brownsville
  - 42019 # West Gulf
  - 42036 # East Gulf
  - 42040 # East Gulf
  - 42055 # Mexico Basin

columns:
  - WVHT
  - DPD
  - APD
  - WTMP
 
units_map:
  WDIR: "degrees (True)"
  WSPD: "m/s"
  GST: "m/s"
  WVHT: "m"
  DPD: "s"
  APD: "s"
  MWD: "degrees (True)"
  PRES: "hPa"
  ATMP: "°C"
  WTMP: "°C"
  DEWP: "°C"
  VIS: "nmi"
  PTDY: "hPa"
  TIDE: "ft"
# Additional mappings can be added here as needed