buoys:
  - 42040
  - 42002
 # - 42005
  - 42036
  - 41009
  - 41002
  - 41013
 # - 42058

columns:
  - WVHT
  - DPD
  - APD
  - WTMP
  
units_map:
  WDIR: "degrees (True)"
  WSPD: "m/s"
  GST: "m/s"
  WVHT: "m"
  DPD: "s"
  APD: "s"
  MWD: "degrees (True)"
  PRES: "hPa"
  ATMP: "°C"
  WTMP: "°C"
  DEWP: "°C"
  VIS: "nmi"
  PTDY: "hPa"
  TIDE: "ft"
  # Additional mappings can be added here as needed
